import { createContext, useState } from "react";

const data = createContext();

export function ProductsData({ children }) {
  const [details] = useState([
    {
      id: 1,
      img: require("../images/Home-1.png"),
      title: "Seaside Serenity Villa",
      desc: "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      dRoom:"04",
      dBath:"03",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Sunset Cove Retreat - Enjoy the ultimate beachfront escape in the Sunset Cove Retreat. With expansive glass walls, panoramic ocean vistas, and a private infinity pool, this home brings modern luxury to the shores.",
      type: "Villa",
      space:"2,500 Square Feet",
      price: "$550,000",
      address: "12 Coastal Serenity Way, Malibu",
      gallery: [
        require("../images/Home-1-1.jpeg"),
        require("../images/Home-1-2.jpeg"),
        require("../images/Home-1-3.jpeg"),
        require("../images/Home-1-4.jpeg"),
        require("../images/Home-1-5.jpeg"),
        require("../images/Home-1-6.jpeg"),
        require("../images/Home-1-7.jpeg"),
        require("../images/Home-1-8.jpeg"),
      ],
    },
    {
      id: 2,
      img: require("../images/Home-2.png"),
      title: "Metropolitan Haven",
      desc: "A chic and fully-furnished 2-bedroom apartment with panoramic city views",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "2-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "2-Bathroom",
      dRoom:"02",
      dBath:"02",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Ocean Breeze Estate - Discover luxury at its finest with the Ocean Breeze Estate. Experience stunning sea views, spacious living areas, and a secluded, lush garden with a tranquil lagoon pool.",
      type: "Villa",
      space:"3,500 Square Feet",
      price: "$350,000",
      address: "34 Seaside Luxe Blvd, Malibu",
      gallery: [
        require("../images/Home-2-1.jpeg"),
        require("../images/Home-2-2.jpeg"),
        require("../images/Home-2-3.jpeg"),
        require("../images/Home-2-4.jpeg"),
        require("../images/Home-2-5.jpeg"),
        require("../images/Home-2-6.jpeg"),
        require("../images/Home-2-7.jpeg"),
        require("../images/Home-2-8.jpeg"),
      ],
    },
    {
      id: 3,
      img: require("../images/Home-3.png"),
      title: "Urban Residences",
      desc: "An elegant 3-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "3-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Tidewater Manor - Escape to the Tidewater Manor, a hidden gem with open-air terraces, a spacious kitchen, and private beach access, offering unparalleled coastal elegance and comfort.",
      type: "Villa",
      space:"1,500 Square Feet",
      price: "$450,000",
      dRoom:"03",
      dBath:"03",
      address: "56 Malibu Oasis Lane, Malibu",
      gallery: [
        require("../images/Home-3-1.jpeg"),
        require("../images/Home-3-2.jpeg"),
        require("../images/Home-3-3.jpeg"),
        require("../images/Home-3-4.jpeg"),
        require("../images/Home-3-5.jpeg"),
        require("../images/Home-3-6.jpeg"),
        require("../images/Home-3-7.jpeg"),
        require("../images/Home-3-8.jpeg"),
      ],
    },

    {
      id: 4,
      img: require("../images/Home-4.jpg"),
      title: "Cityscape Living",
      desc: "An elegant 4-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      dRoom:"04",
      dBath:"03",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Azure Waters Villa - Indulge in coastal luxury at Azure Waters Villa. With sweeping ocean views, designer interiors, and direct beach access, this is a sanctuary of serenity and style.",
      type: "Villa",
      space:"4,500 Square Feet",
      price: "$250,000",
      address: "78 Bayside Dream Dr, Malibu",
      gallery: [
        require("../images/Home-4-1.jpeg"),
        require("../images/Home-4-2.jpeg"),
        require("../images/Home-4-3.jpeg"),
        require("../images/Home-4-4.jpeg"),
        require("../images/Home-4-5.jpeg"),
        require("../images/Home-4-6.jpeg"),
        require("../images/Home-4-7.jpeg"),
        require("../images/Home-4-8.jpeg"),
      ],
    },
    {
      id: 5,
      img: require("../images/Home-5.jpg"),
      title: "Prime Urban Estates",
      desc: "An elegant 4-bedroom, 4-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "4-Bathroom",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      dRoom:"04",
      dBath:"04",
      details:
        "Pacific Horizon House - The Pacific Horizon House offers a chic seaside lifestyle. Enjoy sleek, modern spaces, expansive oceanfront decks, and a beach path just steps away from your door.",
      type: "Villa",
      space:"1,500 Square Feet",
      price: "$650,000",
      address: "90 Ocean View Retreat Ct, Malibu",
      gallery: [
        require("../images/Home-5-1.jpeg"),
        require("../images/Home-5-2.jpeg"),
        require("../images/Home-5-3.jpeg"),
        require("../images/Home-5-4.jpeg"),
        require("../images/Home-5-5.jpeg"),
        require("../images/Home-5-6.jpeg"),
        require("../images/Home-5-7.jpeg"),
        require("../images/Home-5-8.jpeg"),
      ],
    },
    {
      id: 6,
      img: require("../images/Home-6.jpg"),
      title: "Modern Dwellings",
      desc: "An elegant 5-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "5-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Coral Reef Sanctuary - Your seaside paradise awaits at Coral Reef Sanctuary. With lavish open spaces, endless ocean views, and lush landscaping, it's the perfect place to unwind and recharge.",
      type: "Villa",
      dRoom:"05",
      dBath:"03",
      space:"2,600 Square Feet",
      price: "$330,000",
      address: "21 Pacific Horizon Ave, Malibu",
      gallery: [
        require("../images/Home-6-1.jpeg"),
        require("../images/Home-6-2.jpeg"),
        require("../images/Home-6-3.jpeg"),
        require("../images/Home-6-4.jpeg"),
        require("../images/Home-6-5.jpeg"),
        require("../images/Home-6-6.jpeg"),
        require("../images/Home-6-7.jpeg"),
        require("../images/Home-6-8.jpeg"),
      ],
    },
    {
      id: 7,
      img: require("../images/Home-7.jpg"),
      title: "CityView Properties",
      desc: "An elegant 4-bedroom, 2-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "2-Bathroom",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      dRoom:"04",
      dBath:"02",
      details:
        "Shoreline Haven - Experience the epitome of coastal living with Shoreline Haven. Featuring bright, airy rooms, endless oceanfront vistas, and a private garden with beach access, it's a true escape.",
      type: "Villa",
      space:"2,200 Square Feet",
      price: "$360,000",
      address: "43 Surfside Estates Rd, Malibu",
      gallery: [
        require("../images/Home-7-1.jpeg"),
        require("../images/Home-7-2.jpeg"),
        require("../images/Home-7-3.jpeg"),
        require("../images/Home-7-4.jpeg"),
        require("../images/Home-7-5.jpeg"),
        require("../images/Home-7-6.jpeg"),
        require("../images/Home-7-7.jpeg"),
        require("../images/Home-7-8.jpeg"),
      ],
    },
    {
      id: 8,
      img: require("../images/Home-8.jpg"),
      title: "Skyline Residences",
      desc: "An elegant 6-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "6-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      dRoom:"06",
      dBath:"03",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Seabreeze Hideaway - Discover tranquility at Seabreeze Hideaway. This cozy retreat offers panoramic ocean views, spacious living areas, and a lush, secluded garden for ultimate relaxation.",
      type: "Villa",
      space:"3,500 Square Feet",
      price: "$250,000",
      address: "65 Sunny Shores St, Malibu",
      gallery: [
        require("../images/Home-8-1.jpeg"),
        require("../images/Home-8-2.jpeg"),
        require("../images/Home-8-3.jpeg"),
        require("../images/Home-8-4.jpeg"),
        require("../images/Home-8-5.jpeg"),
        require("../images/Home-8-6.jpeg"),
        require("../images/Home-8-7.jpeg"),
        require("../images/Home-8-8.jpeg"),
      ],
    },
    {
      id: 9,
      img: require("../images/Home-9.jpg"),
      title: "Urban Estates Hub",
      desc: "An elegant 5-bedroom, 4-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "5-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "4-Bathroom",
      dRoom:"05",
      dBath:"04",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Lagoon View Villa - The Lagoon View Villa is a blend of luxury and nature. Enjoy serene lagoon views, spacious interiors, and direct access to both the beach and nearby walking trails.",
      type: "Villa",
      space:"2,500 Square Feet",
      price: "$950,000",
      address: "87 Wavecrest Living Pl, Malibu",
      gallery: [
        require("../images/Home-9-1.jpeg"),
        require("../images/Home-9-2.jpeg"),
        require("../images/Home-9-3.jpeg"),
        require("../images/Home-9-4.jpeg"),
        require("../images/Home-9-5.jpeg"),
        require("../images/Home-9-6.jpeg"),
        require("../images/Home-9-7.jpeg"),
        require("../images/Home-9-8.jpeg"),
      ],
    },
    {
      id: 10,
      img: require("../images/Home-10.jpg"),
      title: "Metro Nest Realty",
      desc: "An elegant 4-bedroom, 2-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "2-Bathroom",
      dRoom:"04",
      dBath:"02",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Bayfront Oasis - The Bayfront Oasis offers an unrivaled coastal retreat. With expansive decks, breathtaking bay views, and a private dock, it's designed for those who seek coastal relaxation.",
      type: "Villa",
      space:"2,600 Square Feet",
      price: "$750,000",
      address: "11 Palm Breeze Cres, Malibu",
      gallery: [
        require("../images/Home-10-1.jpeg"),
        require("../images/Home-10-2.jpeg"),
        require("../images/Home-10-3.jpeg"),
        require("../images/Home-10-4.jpeg"),
        require("../images/Home-10-5.jpeg"),
        require("../images/Home-10-6.jpeg"),
        require("../images/Home-10-7.jpeg"),
        require("../images/Home-10-8.jpeg"),
      ],
    },
    {
      id: 11,
      img: require("../images/Home-11.jpg"),
      title: "Metro Nest Realty",
      desc: "An elegant 4-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "4-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      dRoom:"04",
      dBath:"03",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Wavecrest Estate - Wavecrest Estate is a dream come true. With panoramic ocean views, elegant design, and private beach access, it embodies luxury coastal living in every detail.",
      type: "Villa",
      space:"1,500 Square Feet",
      price: "$120,000",
      address: "33 Marina Vista Way, Malibu",
      gallery: [
        require("../images/Home-11-1.jpeg"),
        require("../images/Home-11-2.jpeg"),
        require("../images/Home-11-3.jpeg"),
        require("../images/Home-11-4.jpeg"),
        require("../images/Home-11-5.jpeg"),
        require("../images/Home-11-6.jpeg"),
        require("../images/Home-11-7.jpeg"),
        require("../images/Home-11-8.jpeg"),
      ],
    },
    {
      id: 12,
      img: require("../images/Home-12.jpg"),
      title: "CityLux Homes",
      desc: "An elegant 3-bedroom, 3-bathroom townhouse in a gated community",
      bedRoomIcon: require("../images/Home-1-icon-1.png"),
      bedRooms: "3-Bedroom",
      bathRoomIcon: require("../images/Home-1-icon-2.png"),
      bathRoom: "3-Bathroom",
      dRoom:"03",
      dBath:"03",
      typeIcon: require("../images/Home-1-icon-3.png"),
      areaIcon: require("../images/area-icon.png"),
      details:
        "Oceanview Retreat - Oceanview Retreat is your gateway to paradise. With a modern open floor plan, sweeping ocean vistas, and lush tropical gardens, it's a coastal escape like no other.",
      type: "Villa",
      space:"4,500 Square Feet",
      price: "$230,000",
      address: "55 Coral Reef Villas Blvd, Malibu",
      gallery: [
        require("../images/Home-12-1.jpeg"),
        require("../images/Home-12-2.jpeg"),
        require("../images/Home-12-3.jpeg"),
        require("../images/Home-12-4.jpeg"),
        require("../images/Home-12-5.jpeg"),
        require("../images/Home-12-6.jpeg"),
        require("../images/Home-12-7.jpeg"),
        require("../images/Home-12-8.jpeg"),
      ],
    },
  ]);
  return <data.Provider value={details}>{children}</data.Provider>;
}
export default data;
